@CrudAPI_HostAddress = https://localhost:7272
GET {{CrudAPI_HostAddress}}/api/pessoas

###

POST {{CrudAPI_HostAddress}}/api/pessoas
Content-Type: application/json

{
  //Pessoa
}

###

@id=0
DELETE {{CrudAPI_HostAddress}}/api/pessoas/{{id}}

###

PUT {{CrudAPI_HostAddress}}/api/pessoas/{{id}}
Content-Type: application/json

{
  //Pessoa
}

###
